spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:~/school;DB_CLOSE_ON_EXIT=FALSE
    #url: jdbc:h2:mem:school
    username: sa
    password: ''
    #initialization-mode: always
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:      ddl-auto: update
    show-sql: false
